///////////////////////////////////////////////////////////
//  Order.cs
//  Implementation of the Class Order
//  Generated by Enterprise Architect
//  Created on:      08-дек-2020 18:56:03
//  Original author: Ilya
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Order {

	private List<Car> cars;
	private int id;
	private Customer user;

	public Order(){

	}

	~Order(){

	}

}//end Order